=== RuterNo/tsp-mqtt-schemas/schemas/tspack.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://schema.ruter.no/tspack.json",
  "type": "object",
  "title": "TSP ack MQTT message",
  "description": "For real-time information of a vehicles",
  "required": [
    "eventTimestamp",
    "publishedTimestamp",
    "traceId",
    "vehicleRef",
    "line",
    "journeyPatternRef",
    "triggerPointRef",
    "triggerPointName",
    "triggerPointPosition",
    "priorityLevel"
  ],
  "additionalProperties": false,
  "properties": {
    "eventTimestamp": {
      "$id": "#/properties/eventTimestamp",
      "type": "string",
      "description": "The eventTimestamp of the vm-message that triggered this message. Example: 2019-10-15T09:06:10.285218Z",
      "format": "date-time"
    },
    "publishedTimestamp": {
      "$id": "#/properties/publishedTimestamp",
      "type": "string",
      "description": "Timestamp close to when the TSP-message was generated. ISO 8601 UTC. Example: 2019-10-15T09:06:10.285218Z",
      "format": "date-time"
    },
    "traceId": {
      "$id": "#/properties/traceId",
      "type": "string",
      "description": "trace-id of this message. UUID. example: 40634dfc-b8bc-44b5-9353-161ac0b0e80b"
    },
    "vehicleRef": {
      "$id": "#/properties/vehicleRef",
      "type": "string",
      "description": "Reference to the vehicle. 17-character VIN or 6 character number. Example: XYZ0123X0X0123456 or 123456"
    },
    "line": {
      "$id": "#/properties/line",
      "type": "string",
      "description": "Line number. Example: 36E"
    },
    "journeyPatternRef": {
      "$id": "#/properties/journeyPatternRef",
      "type": "string",
      "description": "Reference to the journey pattern the vehicle is currently driving. Example: RUT:JourneyPattern:123"
    },
    "triggerPointRef": {
      "$id": "#/properties/triggerPointRef",
      "type": "string",
      "description": "Reference to the signal that was triggered"
    },
    "triggerPointName": {
      "$id": "#/properties/triggerPointName",
      "type": "string",
      "description": "Name of the signal/crossroads"
    },
    "triggerPointPosition": {
      "$id": "#/properties/triggerPointPosition",
      "type": "object",
      "description": "Location of of the triggerPoint, GeoJSON geometry object, type Point, WGS84",
      "required": [
        "type",
        "coordinates"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Point"
          ]
        },
        "coordinates": {
          "type": "array",
          "items": [
            {
              "type": "number",
              "description": "longitude"
            },
            {
              "type": "number",
              "description": "latitude"
            }
          ]
        }
      }
    },
    "priorityLevel": {
      "$id": "#/properties/priorityLevel",
      "type": "string",
      "description": "What priority was given"
    }
  }
}

=== RuterNo/tsp-mqtt-schemas/examples/tspack.json
{
  "eventTimestamp": "2019-10-15T09:06:10.285218Z",
  "publishedTimestamp": "2019-10-15T09:06:15.285218Z",
  "traceId": "40634dfc-b8bc-44b5-9353-161ac0b0e80b",
  "vehicleRef": "XYZ0123X0X0123456",
  "line": "36E",
  "journeyPatternRef": "RUT:JourneyPattern:123",
  "triggerPointRef":  "?",
  "triggerPointName":  "?",
  "triggerPointPosition": {
    "type": "Point",
    "coordinates": [10.7522, 59.9139]
  },
  "priorityLevel": "?"
}
