=== RuterNo/tsp-mqtt-schemas/schemas/vehiclemonitoring.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://schema.ruter.no/vehiclemonitoring.json",
  "type": "object",
  "title": "Vehicle Monitoring MQTT message",
  "description": "For real-time information of a vehicles",
  "required": [
    "eventTimestamp",
    "publishedTimestamp",
    "traceId",
    "vehicleRef",
    "journeyPatternRef",
    "quayRef",
    "order",
    "distanceMeter",
    "position",
    "delaySeconds",
    "doorsOpen"
  ],
  "additionalProperties": false,
  "properties": {
    "eventTimestamp": {
      "$id": "#/properties/eventTimestamp",
      "type": "string",
      "description": "Timestamp of the event that triggered this message. ISO 8601 UTC. Example: 2019-10-15T09:06:10.285218Z",
      "format": "date-time"
    },
    "publishedTimestamp": {
      "$id": "#/properties/publishedTimestamp",
      "type": "string",
      "description": "Timestamp close to when the message was generated. ISO 8601 UTC. Example: 2019-10-15T09:06:10.285218Z",
      "format": "date-time"
    },
    "traceId": {
      "$id": "#/properties/traceId",
      "type": "string",
      "description": "trace-id of this message. UUID. example: 40634dfc-b8bc-44b5-9353-161ac0b0e80b"
    },
    "vehicleRef": {
      "$id": "#/properties/vehicleRef",
      "type": "string",
      "description": "Reference to the vehicle. 16-character VIN or 8 character number. Example: XYZ0123X0X0123456 or 123456"
    },
    "journeyPatternRef": {
      "$id": "#/properties/journeyPatternRef",
      "type": "string",
      "description": "Reference to the journey pattern the vehicle is currently driving. Example: RUT:JourneyPattern:123"
    },
    "quayRef": {
      "$id": "#/properties/quayRef",
      "type": "string",
      "description": "Reference to the quay that the vehicle is currently at or driving towards. Example: NSR:Quay:123"
    },
    "order": {
      "$id": "#/properties/order",
      "type": "integer",
      "description": "The order of the quay that the vehicle is currently at or driving towards, starting at 1"
    },
    "position": {
      "$id": "#/properties/position",
      "type": "array",
      "description": "cordinates of the vehicle, as defined by GeoJson type Point: [longitude, latitude]",
      "items": [
        {
          "type": "number",
          "description": "longitude"
        },
        {
          "type": "number",
          "description": "latitude"
        }
      ]
    },
    "distanceMeter": {
      "$id": "#/properties/distanceMeter",
      "type": "number",
      "description": "The distance driven towards the quay that the vehicle is currently at or driving towards. In meter. Note: approximate if odometer is missing"
    },
    "occupancyPercent": {
      "$id": "#/properties/occupancyPercent",
      "type": "integer",
      "description": "The occupancy of the bus delivered in percent"
    },
    "delaySeconds": {
      "$id": "#/properties/delaySeconds",
      "type": "integer",
      "description": "The current delay of the vehicle compared to the plan, in seconds"
    },
    "doorsOpen": {
      "$id": "#/properties/doorsOpen",
      "type": "boolean",
      "description": "true if one or more doors are open"
    }
  }
}

=== RuterNo/tsp-mqtt-schemas/examples/vehiclemonitoring.json
{
  "eventTimestamp": "2019-10-15T09:06:10.285218Z",
  "publishedTimestamp": "2019-10-15T09:06:15.285218Z",
  "traceId": "40634dfc-b8bc-44b5-9353-161ac0b0e80b",
  "vehicleRef": "XYZ0123X0X0123456",
  "journeyPatternRef": "RUT:JourneyPattern:123",
  "quayRef": "NSR:Quay:123",
  "order": 1,
  "distanceMeter": 32.5,
  "position": [10.7522, 59.9139],
  "delaySeconds": -10,
  "doorsOpen": false
}
